project:
  type: website
  output-dir: docs

website:
  title: "ULRBf"
  navbar:
    background: "dark"
    foreground: "light"
    search : true
    left:
      - Me.qmd
      - Task.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


