project:
  type: website
  output-dir: docs

website:
  title: "Ulrb_test"
  search: true
  navbar:
    # title : "Second"
    background : primary
    search : true
    left:
      # - href: index.qmd
      - text: "Home"
        file : index.qmd
      - talks.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



