project:
  type: website
  output-dir: docs

website:
  title: "Ulrb_test"
  navbar:
    background: "dark"
    foreground: "light"
    # title : "Second"
    # background : primary
    search : true
    left:
      # - href: index.qmd
      - text: "Home"
        file : index.qmd
      - Listing Example.qmd
      # - about.qmd
      - Finley Malloc.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


